'use strict';

const path   = require('path');
const fs     = require('fs');
const zlib   = require('zlib');
const crypto = require('crypto');
const { spawnSync } = require('child_process');

const isPackaged = typeof process.pkg !== 'undefined';

const FFMPEG_BIN  = process.platform === 'win32' ? 'ffmpeg.exe'  : 'ffmpeg';
const FFPROBE_BIN = process.platform === 'win32' ? 'ffprobe.exe' : 'ffprobe';

let ffmpegPath  = 'ffmpeg';
let ffprobePath = 'ffprobe';

if (isPackaged) {
  const dataRoot    = path.dirname(process.execPath);
  const binDir      = path.join(dataRoot, 'bin');
  const ffmpegDest  = path.join(binDir, FFMPEG_BIN);
  const ffprobeDest = path.join(binDir, FFPROBE_BIN);

  function sha256(buf) {
    return crypto.createHash('sha256').update(buf).digest('hex');
  }

  function entryBuffer(entry) {
    if (Buffer.isBuffer(entry.data)) return entry.data;
    if (Array.isArray(entry.data)) return Buffer.from(entry.data.join(''), 'base64');
    if (typeof entry.data === 'string') return Buffer.from(entry.data, 'base64');
    throw new Error(`invalid bundle data for ${entry.filename || 'FFmpeg binary'}`);
  }

  function entryIsCompressed(entry) {
    return entry.compressed === true || entry.compression === 'gzip';
  }

  function entryRawBuffer(entry) {
    const data = entryBuffer(entry);
    return entryIsCompressed(entry) ? zlib.gunzipSync(data) : data;
  }

  function extractEntry(entry, dest) {
    const raw = entryRawBuffer(entry);
    if (entry.sha256 && sha256(raw) !== entry.sha256) {
      throw new Error(`hash mismatch for ${path.basename(dest)}`);
    }
    fs.writeFileSync(dest, raw, { mode: 0o755 });
  }

  function needsExtract(dest, entry) {
    if (!fs.existsSync(dest)) return true;
    if (!entry.sha256) return false;
    try {
      const raw = entryRawBuffer(entry);
      return sha256(fs.readFileSync(dest)) !== sha256(raw);
    } catch {
      return true;
    }
  }

  try {
    // pkg.assets globs are broken for node20 targets. FFmpeg is embedded in
    // src/ffmpeg-bundle.js (generated by scripts/generate-ffmpeg-bundle.js).
    const bundle = require('../ffmpeg-bundle');
    fs.mkdirSync(binDir, { recursive: true });

    const ffmpegEntry = bundle.ffmpeg || bundle.binaries?.ffmpeg;
    const ffprobeEntry = bundle.ffprobe || bundle.binaries?.ffprobe;
    if (!ffmpegEntry || !ffprobeEntry) {
      throw new Error('ffmpeg-bundle.js is missing ffmpeg or ffprobe');
    }

    if (needsExtract(ffmpegDest, ffmpegEntry)) {
      extractEntry(ffmpegEntry, ffmpegDest);
    }
    if (needsExtract(ffprobeDest, ffprobeEntry)) {
      extractEntry(ffprobeEntry, ffprobeDest);
    }
    console.log(`[Paperweight] FFmpeg ready in ${binDir}`);
  } catch (err) {
    console.warn(`[Paperweight] Could not extract bundled FFmpeg: ${err.message}`);
  }

  if (fs.existsSync(ffmpegDest))  ffmpegPath  = ffmpegDest;
  if (fs.existsSync(ffprobeDest)) ffprobePath = ffprobeDest;
} else {
  const vendorDir = path.join(__dirname, '../../vendor/ffmpeg');
  const vendorFfmpeg = path.join(vendorDir, FFMPEG_BIN);
  const vendorFfprobe = path.join(vendorDir, FFPROBE_BIN);
  if (fs.existsSync(vendorFfmpeg))  ffmpegPath  = vendorFfmpeg;
  if (fs.existsSync(vendorFfprobe)) ffprobePath = vendorFfprobe;
}

function installHint() {
  if (isPackaged) {
    return 'FFmpeg could not be extracted from the bundle. Try reinstalling Paperweight.';
  }
  if (process.platform === 'win32') {
    return 'Install FFmpeg with: winget install Gyan.FFmpeg, then reopen Paperweight.';
  }
  if (process.platform === 'darwin') {
    return 'Install FFmpeg with: brew install ffmpeg, then restart Paperweight.';
  }
  return 'Install FFmpeg with your package manager, for example: sudo apt install ffmpeg, then restart Paperweight.';
}

function commandVersion(binPath) {
  try {
    const result = spawnSync(binPath, ['-version'], {
      stdio: 'pipe',
      windowsHide: true,
      timeout: 3000,
      encoding: 'utf8',
    });
    if (result.status !== 0) return null;
    return String(result.stdout || '').split(/\r?\n/)[0] || `${binPath} found`;
  } catch {
    return null;
  }
}

function getFFmpegStatus() {
  const ffmpeg  = commandVersion(ffmpegPath);
  const ffprobe = commandVersion(ffprobePath);
  const missing = [];
  if (!ffmpeg)  missing.push('ffmpeg');
  if (!ffprobe) missing.push('ffprobe');

  return {
    ok: missing.length === 0,
    ffmpeg,
    ffprobe,
    missing,
    message: missing.length
      ? `${missing.join(' and ')} not found. ${installHint()}`
      : 'FFmpeg and ffprobe are available.',
  };
}

module.exports = { ffmpegPath, ffprobePath, commandVersion, getFFmpegStatus, installHint };
