'use strict';

const path   = require('path');
const fs     = require('fs');
const { spawnSync } = require('child_process');
const { ensureExtracted } = require('./bundle-extract');

const isPackaged = typeof process.pkg !== 'undefined';
const isElectron = process.env.PAPERWEIGHT_ELECTRON === 'true';

const FFMPEG_BIN  = process.platform === 'win32' ? 'ffmpeg.exe'  : 'ffmpeg';
const FFPROBE_BIN = process.platform === 'win32' ? 'ffprobe.exe' : 'ffprobe';

let ffmpegPath  = 'ffmpeg';
let ffprobePath = 'ffprobe';

if (isPackaged) {
  const dataRoot    = path.dirname(process.execPath);
  const binDir      = path.join(dataRoot, 'bin');
  const ffmpegDest  = path.join(binDir, FFMPEG_BIN);
  const ffprobeDest = path.join(binDir, FFPROBE_BIN);

  try {
    // pkg.assets globs are broken for node20 targets. FFmpeg is embedded in
    // src/ffmpeg-bundle.js (generated by scripts/generate-ffmpeg-bundle.js).
    const bundle = require('../ffmpeg-bundle');
    const ffmpegEntry = bundle.ffmpeg || bundle.binaries?.ffmpeg;
    const ffprobeEntry = bundle.ffprobe || bundle.binaries?.ffprobe;
    if (!ffmpegEntry || !ffprobeEntry) {
      throw new Error('ffmpeg-bundle.js is missing ffmpeg or ffprobe');
    }

    if (ensureExtracted(ffmpegEntry, ffmpegDest) && ensureExtracted(ffprobeEntry, ffprobeDest)) {
      console.log(`[Paperweight] FFmpeg ready in ${binDir}`);
    } else {
      throw new Error('extraction did not produce both binaries');
    }
  } catch (err) {
    console.warn(`[Paperweight] Could not extract bundled FFmpeg: ${err.message}`);
  }

  if (fs.existsSync(ffmpegDest))  ffmpegPath  = ffmpegDest;
  if (fs.existsSync(ffprobeDest)) ffprobePath = ffprobeDest;
} else if (isElectron && process.resourcesPath) {
  // A packaged Electron build stages ffmpeg/ffprobe into extraResources
  // (electron/package.json, populated by scripts/stage-electron-ffmpeg.js) —
  // process.resourcesPath is that extraResources root at runtime. In dev mode
  // (electron main.js, not packaged) nothing is staged there, so this falls
  // through to the vendor/PATH branch below like the plain-Node case.
  const electronBinDir = path.join(process.resourcesPath, 'bin');
  const electronFfmpeg = path.join(electronBinDir, FFMPEG_BIN);
  const electronFfprobe = path.join(electronBinDir, FFPROBE_BIN);
  if (fs.existsSync(electronFfmpeg))  ffmpegPath  = electronFfmpeg;
  if (fs.existsSync(electronFfprobe)) ffprobePath = electronFfprobe;

  if (!fs.existsSync(electronFfmpeg) || !fs.existsSync(electronFfprobe)) {
    const vendorDir = path.join(__dirname, '../../vendor/ffmpeg');
    const vendorFfmpeg = path.join(vendorDir, FFMPEG_BIN);
    const vendorFfprobe = path.join(vendorDir, FFPROBE_BIN);
    if (!fs.existsSync(electronFfmpeg) && fs.existsSync(vendorFfmpeg))   ffmpegPath  = vendorFfmpeg;
    if (!fs.existsSync(electronFfprobe) && fs.existsSync(vendorFfprobe)) ffprobePath = vendorFfprobe;
  }
} else {
  const vendorDir = path.join(__dirname, '../../vendor/ffmpeg');
  const vendorFfmpeg = path.join(vendorDir, FFMPEG_BIN);
  const vendorFfprobe = path.join(vendorDir, FFPROBE_BIN);
  if (fs.existsSync(vendorFfmpeg))  ffmpegPath  = vendorFfmpeg;
  if (fs.existsSync(vendorFfprobe)) ffprobePath = vendorFfprobe;
}

function installHint() {
  if (isPackaged) {
    return 'FFmpeg could not be extracted from the bundle. Try reinstalling Paperweight.';
  }
  if (process.platform === 'win32') {
    return 'Install FFmpeg with: winget install Gyan.FFmpeg, then reopen Paperweight.';
  }
  if (process.platform === 'darwin') {
    return 'Install FFmpeg with: brew install ffmpeg, then restart Paperweight.';
  }
  return 'Install FFmpeg with your package manager, for example: sudo apt install ffmpeg, then restart Paperweight.';
}

function commandVersion(binPath) {
  try {
    const result = spawnSync(binPath, ['-version'], {
      stdio: 'pipe',
      windowsHide: true,
      timeout: 3000,
      encoding: 'utf8',
    });
    if (result.status !== 0) return null;
    return String(result.stdout || '').split(/\r?\n/)[0] || `${binPath} found`;
  } catch {
    return null;
  }
}

function getFFmpegStatus() {
  const ffmpeg  = commandVersion(ffmpegPath);
  const ffprobe = commandVersion(ffprobePath);
  const missing = [];
  if (!ffmpeg)  missing.push('ffmpeg');
  if (!ffprobe) missing.push('ffprobe');

  return {
    ok: missing.length === 0,
    ffmpeg,
    ffprobe,
    missing,
    message: missing.length
      ? `${missing.join(' and ')} not found. ${installHint()}`
      : 'FFmpeg and ffprobe are available.',
  };
}

module.exports = { ffmpegPath, ffprobePath, commandVersion, getFFmpegStatus, installHint };
