import { useState } from 'react';
import { ShieldCheck } from 'lucide-react';

import { ViewHeader } from '@/components/primitives';
import { cn } from '@/lib/utils';

export function Security({ onNotify }: { onNotify: (message: string) => void }) {
  const [twoFactor, setTwoFactor] = useState(true);
  return <div className="animate-enter"><ViewHeader eyebrow="Account / Security" title="Keep the room safe." description="Your account, your listeners, your unreleased work — protected without getting in the way." /><div className="max-w-3xl space-y-4"><section className="panel rounded-2xl p-5 sm:p-6"><div className="flex items-start gap-4"><span className="h-10 w-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center"><ShieldCheck size={19} /></span><div className="flex-1"><h2 className="font-display text-xl font-semibold">Two-factor authentication</h2><p className="text-sm text-muted-foreground mt-1">Add another lock before anyone reaches your studio.</p></div><button type="button" role="switch" aria-checked={twoFactor} data-testid="toggle-two-factor" onClick={() => { setTwoFactor(!twoFactor); onNotify(twoFactor ? 'Two-factor authentication disabled.' : 'Two-factor authentication enabled.'); }} className={cn('h-7 w-12 rounded-full p-1 transition-colors', twoFactor ? 'bg-primary' : 'bg-white/15')}><span className={cn('block h-5 w-5 rounded-full bg-[#171a28] transition-transform', twoFactor ? 'translate-x-5' : 'translate-x-0')} /></button></div><div className="mt-5 pl-14 text-xs text-primary">{twoFactor ? 'Enabled · Authenticator app' : 'Not enabled'}</div></section>{[['Password', 'Last changed 42 days ago', 'Update password'], ['Active sessions', '2 devices · New York, NY and this Mac', 'Manage sessions'], ['Connected apps', 'OBS Studio · connected 3 days ago', 'Review apps']].map((item, i) => <section key={item[0]} className="panel rounded-2xl p-5 sm:p-6 flex items-center gap-4"><div className="flex-1"><h2 className="font-medium text-sm">{item[0]}</h2><p className="text-xs text-muted-foreground mt-1">{item[1]}</p></div><button type="button" data-testid={`button-security-${i}`} onClick={() => onNotify(`${item[0]} settings opened.`)} className="ghost-button rounded-lg px-3 py-2 text-xs">{item[2]}</button></section>)}<button type="button" data-testid="button-sign-out-all" onClick={() => onNotify('All other sessions have been signed out.')} className="text-xs text-destructive px-1 py-3">Sign out of all other sessions</button></div></div>;
}
