import { useState } from 'react';
import { Settings, Wallet } from 'lucide-react';

import { ViewHeader } from '@/components/primitives';
import { cn } from '@/lib/utils';

export function SettingsView({ onNotify }: { onNotify: (message: string) => void }) {
  const [motion, setMotion] = useState(true);
  const [privateProfile, setPrivateProfile] = useState(false);
  const toggles = [{ label: 'Motion', body: 'Keep the studio’s small movements alive.', value: motion, set: setMotion }, { label: 'Private profile', body: 'Hide your public profile while you work.', value: privateProfile, set: setPrivateProfile }];
  return <div className="animate-enter"><ViewHeader eyebrow="Account / Settings" title="Your studio, your rules." description="Quiet preferences that make this workspace feel like yours." /><div className="max-w-3xl space-y-4"><section className="panel rounded-2xl p-5 sm:p-6"><div className="flex items-center gap-3 mb-5"><Settings size={18} className="text-primary" /><h2 className="font-display text-xl font-semibold">Workspace preferences</h2></div>{toggles.map((toggle) => <div key={toggle.label} className="flex items-center gap-4 py-4 border-t border-white/[.08]"><div className="flex-1"><p className="text-sm">{toggle.label}</p><p className="text-xs text-muted-foreground mt-1">{toggle.body}</p></div><button type="button" role="switch" aria-checked={toggle.value} data-testid={`toggle-${toggle.label.toLowerCase().replaceAll(' ', '-')}`} onClick={() => toggle.set(!toggle.value)} className={cn('h-7 w-12 rounded-full p-1 transition-colors', toggle.value ? 'bg-primary' : 'bg-white/15')}><span className={cn('block h-5 w-5 rounded-full bg-[#171a28] transition-transform', toggle.value ? 'translate-x-5' : 'translate-x-0')} /></button></div>)}</section><section className="panel rounded-2xl p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="font-display text-lg font-semibold">Notifications</p><p className="text-xs text-muted-foreground mt-1">A digest of the signals you care about.</p></div><button type="button" data-testid="button-notification-preferences" onClick={() => onNotify('Notification preferences saved.')} className="ghost-button rounded-lg px-3 py-2 text-xs">Configure</button></div><div className="flex flex-wrap gap-2 mt-5">{['New subscribers', 'Release milestones', 'Payouts', 'Broadcast reminders'].map((item) => <span key={item} className="rounded-full bg-primary/10 text-primary px-3 py-1.5 text-[11px]">{item}</span>)}</div></section><section className="panel rounded-2xl p-5 sm:p-6"><div className="flex items-center gap-3"><Wallet size={17} className="text-accent" /><div><p className="font-display text-lg font-semibold">Plan & billing</p><p className="text-xs text-muted-foreground mt-1">Creator Pro · $12 / month · renews Apr 04</p></div><button type="button" data-testid="button-manage-billing" onClick={() => onNotify('Billing portal opened.')} className="ghost-button rounded-lg px-3 py-2 text-xs ml-auto">Manage</button></div></section></div></div>;
}
