import { Aperture, ArrowUpRight, CircleHelp, ListMusic, Share2, Tags } from 'lucide-react';

import { ViewHeader } from '@/components/primitives';
import type { ModalKey } from '@/types';

export function Tools({ onNotify, onOpen }: { onNotify: (message: string) => void; onOpen: (modal: ModalKey) => void }) {
  const tools = [{ icon: ListMusic, title: 'Smart playlists', body: 'Auto-sort your catalog by mood, play count, or release date.', action: 'Build playlist' }, { icon: Aperture, title: 'Preview scheduler', body: 'Give subscribers a first listen before the public release.', action: 'Schedule a preview' }, { icon: Tags, title: 'Release notes', body: 'Add context, credits, and the story behind each drop.', action: 'Write release notes' }, { icon: Share2, title: 'Share kit', body: 'A focused link for the next thing you want people to hear.', action: 'Create share link' }];
  return <div className="animate-enter"><ViewHeader eyebrow="Identity / Tools" title="Small tools, sharp edges." description="The pieces that make publishing feel less like paperwork and more like a practice." /><div className="grid md:grid-cols-2 gap-4">{tools.map((tool, i) => { const Icon = tool.icon; return <section className="panel rounded-2xl p-5 sm:p-6 flex flex-col min-h-52" key={tool.title}><span className="h-10 w-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center"><Icon size={18} /></span><h2 className="font-display text-xl font-semibold mt-5">{tool.title}</h2><p className="text-sm text-muted-foreground mt-2 max-w-sm">{tool.body}</p><button type="button" data-testid={`button-tool-${i}`} onClick={() => i === 3 ? onOpen('share') : i === 1 ? onOpen('live') : onNotify(`${tool.title} opened.`)} className="text-xs text-primary mt-auto pt-6 flex items-center gap-1">{tool.action} <ArrowUpRight size={14} /></button></section>; })}</div><section className="panel rounded-2xl p-5 sm:p-6 mt-6"><div className="flex items-start gap-3"><CircleHelp size={18} className="text-accent" /><div><h2 className="font-display text-lg font-semibold">Need a hand with the release?</h2><p className="text-sm text-muted-foreground mt-1">Read the short guide to making your next drop feel like an event.</p><button type="button" data-testid="button-read-release-guide" onClick={() => onNotify('Release guide opened in a new reading view.')} className="text-xs text-primary mt-4">Read the guide <ArrowUpRight size={13} className="inline ml-1" /></button></div></div></section></div>;
}
